version: '2.1'

services:
  validator:
    image: validator
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 30399:30399
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 ./app